trigger:
- azure-pipelines #rama dónde se trabajaron los test

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run test-ci
    npm run build
  displayName: 'npm install, test and build'

